#include "simulator.h"

#ifdef SIMULATOR

void *SCnSCB_BASE;
void *SCB_BASE;
void *SysTick_BASE;
void *NVIC_BASE;
void *ITM_BASE;
void *DWT_BASE;
void *TPI_BASE;
void *CoreDebug_BASE;
void *MPU_BASE;
void *FPU_BASE;
void *TIM2_BASE;
void *TIM3_BASE;
void *TIM4_BASE;
void *TIM5_BASE;
void *TIM6_BASE;
void *TIM7_BASE;
void *TIM13_BASE;
void *TIM14_BASE;
void *VREFBUF_BASE;
void *RTC_BASE;
void *WWDG1_BASE;
void *IWDG1_BASE;
void *SPI2_BASE;
void *SPI3_BASE;
void *SPI4_BASE;
void *SPI5_BASE;
void *SPI6_BASE;
void *USART2_BASE;
void *USART3_BASE;
void *USART6_BASE;
void *USART10_BASE;
void *UART7_BASE;
void *UART8_BASE;
void *UART9_BASE;
void *CRS_BASE;
void *UART4_BASE;
void *UART5_BASE;
void *I2C1_BASE;
void *I2C2_BASE;
void *I2C3_BASE;
void *I2C4_BASE;
void *I2C5_BASE;
void *FDCAN1_BASE;
void *FDCAN2_BASE;
void *FDCAN_CCU_BASE;
void *FDCAN3_BASE;
void *TIM23_BASE;
void *TIM24_BASE;
void *CEC_BASE;
void *LPTIM1_BASE;
void *PWR_BASE;
void *DAC1_BASE;
void *LPUART1_BASE;
void *SWPMI1_BASE;
void *LPTIM4_BASE;
void *LPTIM5_BASE;
void *SYSCFG_BASE;
void *COMP12_BASE;
void *COMP1_BASE;
void *COMP2_BASE;
void *COMP12_COMMON_BASE;
void *OPAMP_BASE;
void *OPAMP1_BASE;
void *OPAMP2_BASE;
void *EXTI_BASE;
void *EXTI_D1_BASE;
void *EXTI_D2_BASE;
void *TIM1_BASE;
void *SPI1_BASE;
void *TIM8_BASE;
void *USART1_BASE;
void *TIM12_BASE;
void *TIM15_BASE;
void *TIM16_BASE;
void *TIM17_BASE;
void *SAI1_BASE;
void *SAI1_Block_A_BASE;
void *SAI1_Block_B_BASE;
void *SAI4_BASE;
void *SAI4_Block_A_BASE;
void *SAI4_Block_B_BASE;
void *SPDIFRX_BASE;
void *DFSDM1_Channel0_BASE;
void *DFSDM1_Channel1_BASE;
void *DFSDM1_Channel2_BASE;
void *DFSDM1_Channel3_BASE;
void *DFSDM1_Channel4_BASE;
void *DFSDM1_Channel5_BASE;
void *DFSDM1_Channel6_BASE;
void *DFSDM1_Channel7_BASE;
void *DFSDM1_Filter0_BASE;
void *DFSDM1_Filter1_BASE;
void *DFSDM1_Filter2_BASE;
void *DFSDM1_Filter3_BASE;
void *DMA2D_BASE;
void *DCMI_BASE;
void *PSSI_BASE;
void *RCC_BASE;
void *FLASH_BASE;
void *CRC_BASE;
void *GPIOA_BASE;
void *GPIOB_BASE;
void *GPIOC_BASE;
void *GPIOD_BASE;
void *GPIOE_BASE;
void *GPIOF_BASE;
void *GPIOG_BASE;
void *GPIOH_BASE;
void *GPIOJ_BASE;
void *GPIOK_BASE;
void *ADC1_BASE;
void *ADC2_BASE;
void *ADC3_BASE;
void *ADC3_COMMON_BASE;
void *ADC12_COMMON_BASE;
void *RNG_BASE;
void *SDMMC2_BASE;
void *DLYB_SDMMC2_BASE;
void *FMAC_BASE;
void *CORDIC_BASE;
void *BDMA_BASE;
void *BDMA_Channel0_BASE;
void *BDMA_Channel1_BASE;
void *BDMA_Channel2_BASE;
void *BDMA_Channel3_BASE;
void *BDMA_Channel4_BASE;
void *BDMA_Channel5_BASE;
void *BDMA_Channel6_BASE;
void *BDMA_Channel7_BASE;
void *RAMECC1_BASE;
void *RAMECC1_Monitor1_BASE;
void *RAMECC1_Monitor2_BASE;
void *RAMECC1_Monitor3_BASE;
void *RAMECC1_Monitor4_BASE;
void *RAMECC1_Monitor5_BASE;
void *RAMECC1_Monitor6_BASE;
void *RAMECC2_BASE;
void *RAMECC2_Monitor1_BASE;
void *RAMECC2_Monitor2_BASE;
void *RAMECC2_Monitor3_BASE;
void *RAMECC3_BASE;
void *RAMECC3_Monitor1_BASE;
void *RAMECC3_Monitor2_BASE;
void *DMAMUX2_BASE;
void *DMAMUX2_Channel0_BASE;
void *DMAMUX2_Channel1_BASE;
void *DMAMUX2_Channel2_BASE;
void *DMAMUX2_Channel3_BASE;
void *DMAMUX2_Channel4_BASE;
void *DMAMUX2_Channel5_BASE;
void *DMAMUX2_Channel6_BASE;
void *DMAMUX2_Channel7_BASE;
void *DMAMUX2_RequestGenerator0_BASE;
void *DMAMUX2_RequestGenerator1_BASE;
void *DMAMUX2_RequestGenerator2_BASE;
void *DMAMUX2_RequestGenerator3_BASE;
void *DMAMUX2_RequestGenerator4_BASE;
void *DMAMUX2_RequestGenerator5_BASE;
void *DMAMUX2_RequestGenerator6_BASE;
void *DMAMUX2_RequestGenerator7_BASE;
void *DMAMUX2_ChannelStatus_BASE;
void *DMAMUX2_RequestGenStatus_BASE;
void *DMA2_BASE;
void *DMA2_Stream0_BASE;
void *DMA2_Stream1_BASE;
void *DMA2_Stream2_BASE;
void *DMA2_Stream3_BASE;
void *DMA2_Stream4_BASE;
void *DMA2_Stream5_BASE;
void *DMA2_Stream6_BASE;
void *DMA2_Stream7_BASE;
void *DMA1_BASE;
void *DMA1_Stream0_BASE;
void *DMA1_Stream1_BASE;
void *DMA1_Stream2_BASE;
void *DMA1_Stream3_BASE;
void *DMA1_Stream4_BASE;
void *DMA1_Stream5_BASE;
void *DMA1_Stream6_BASE;
void *DMA1_Stream7_BASE;
void *DMAMUX1_BASE;
void *DMAMUX1_Channel0_BASE;
void *DMAMUX1_Channel1_BASE;
void *DMAMUX1_Channel2_BASE;
void *DMAMUX1_Channel3_BASE;
void *DMAMUX1_Channel4_BASE;
void *DMAMUX1_Channel5_BASE;
void *DMAMUX1_Channel6_BASE;
void *DMAMUX1_Channel7_BASE;
void *DMAMUX1_Channel8_BASE;
void *DMAMUX1_Channel9_BASE;
void *DMAMUX1_Channel10_BASE;
void *DMAMUX1_Channel11_BASE;
void *DMAMUX1_Channel12_BASE;
void *DMAMUX1_Channel13_BASE;
void *DMAMUX1_Channel14_BASE;
void *DMAMUX1_Channel15_BASE;
void *DMAMUX1_RequestGenerator0_BASE;
void *DMAMUX1_RequestGenerator1_BASE;
void *DMAMUX1_RequestGenerator2_BASE;
void *DMAMUX1_RequestGenerator3_BASE;
void *DMAMUX1_RequestGenerator4_BASE;
void *DMAMUX1_RequestGenerator5_BASE;
void *DMAMUX1_RequestGenerator6_BASE;
void *DMAMUX1_RequestGenerator7_BASE;
void *DMAMUX1_ChannelStatus_BASE;
void *DMAMUX1_RequestGenStatus_BASE;
void *FMC_Bank1_R_BASE;
void *FMC_Bank1E_R_BASE;
void *FMC_Bank2_R_BASE;
void *FMC_Bank3_R_BASE;
void *FMC_Bank5_6_R_BASE;
void *OCTOSPI1_BASE;
void *DLYB_OCTOSPI1_BASE;
void *OCTOSPI2_BASE;
void *DLYB_OCTOSPI2_BASE;
void *OCTOSPIM_BASE;
void *SDMMC1_BASE;
void *DLYB_SDMMC1_BASE;
void *DBGMCU_BASE;
void *HSEM_BASE;
void *HSEM_COMMON_BASE;
void *LTDC_BASE;
void *LTDC_Layer1_BASE;
void *LTDC_Layer2_BASE;
void *MDIOS_BASE;
void *ETH_BASE;
void *MDMA_BASE;
void *MDMA_Channel0_BASE;
void *MDMA_Channel1_BASE;
void *MDMA_Channel2_BASE;
void *MDMA_Channel3_BASE;
void *MDMA_Channel4_BASE;
void *MDMA_Channel5_BASE;
void *MDMA_Channel6_BASE;
void *MDMA_Channel7_BASE;
void *MDMA_Channel8_BASE;
void *MDMA_Channel9_BASE;
void *MDMA_Channel10_BASE;
void *MDMA_Channel11_BASE;
void *MDMA_Channel12_BASE;
void *MDMA_Channel13_BASE;
void *MDMA_Channel14_BASE;
void *MDMA_Channel15_BASE;
void *USB1_OTG_HS_BASE;
void *GPV_BASE;

void *Simulator_arena_base;

void Simulator_InitMemory(void *rawmem)
{
  Simulator_Memory *mem = (Simulator_Memory*)rawmem;

  SCnSCB_BASE = mem->SCnSCB_base;
  SCB_BASE = mem->SCB_base;
  SysTick_BASE = mem->SysTick_base;
  NVIC_BASE = mem->NVIC_base;
  ITM_BASE = mem->ITM_base;
  DWT_BASE = mem->DWT_base;
  TPI_BASE = mem->TPI_base;
  CoreDebug_BASE = mem->CoreDebug_base;
  MPU_BASE = mem->MPU_base;
  FPU_BASE = mem->FPU_base;
  TIM2_BASE = mem->TIM2_base;
  TIM3_BASE = mem->TIM3_base;
  TIM4_BASE = mem->TIM4_base;
  TIM5_BASE = mem->TIM5_base;
  TIM6_BASE = mem->TIM6_base;
  TIM7_BASE = mem->TIM7_base;
  TIM13_BASE = mem->TIM13_base;
  TIM14_BASE = mem->TIM14_base;
  VREFBUF_BASE = mem->VREFBUF_base;
  RTC_BASE = mem->RTC_base;
  WWDG1_BASE = mem->WWDG1_base;
  IWDG1_BASE = mem->IWDG1_base;
  SPI2_BASE = mem->SPI2_base;
  SPI3_BASE = mem->SPI3_base;
  SPI4_BASE = mem->SPI4_base;
  SPI5_BASE = mem->SPI5_base;
  SPI6_BASE = mem->SPI6_base;
  USART2_BASE = mem->USART2_base;
  USART3_BASE = mem->USART3_base;
  USART6_BASE = mem->USART6_base;
  USART10_BASE = mem->USART10_base;
  UART7_BASE = mem->UART7_base;
  UART8_BASE = mem->UART8_base;
  UART9_BASE = mem->UART9_base;
  CRS_BASE = mem->CRS_base;
  UART4_BASE = mem->UART4_base;
  UART5_BASE = mem->UART5_base;
  I2C1_BASE = mem->I2C1_base;
  I2C2_BASE = mem->I2C2_base;
  I2C3_BASE = mem->I2C3_base;
  I2C4_BASE = mem->I2C4_base;
  I2C5_BASE = mem->I2C5_base;
  FDCAN1_BASE = mem->FDCAN1_base;
  FDCAN2_BASE = mem->FDCAN2_base;
  FDCAN_CCU_BASE = mem->FDCAN_CCU_base;
  FDCAN3_BASE = mem->FDCAN3_base;
  TIM23_BASE = mem->TIM23_base;
  TIM24_BASE = mem->TIM24_base;
  CEC_BASE = mem->CEC_base;
  LPTIM1_BASE = mem->LPTIM1_base;
  PWR_BASE = mem->PWR_base;
  DAC1_BASE = mem->DAC1_base;
  LPUART1_BASE = mem->LPUART1_base;
  SWPMI1_BASE = mem->SWPMI1_base;
  LPTIM4_BASE = mem->LPTIM4_base;
  LPTIM5_BASE = mem->LPTIM5_base;
  SYSCFG_BASE = mem->SYSCFG_base;
  COMP12_BASE = mem->COMP12_base;
  COMP1_BASE = mem->COMP1_base;
  COMP2_BASE = mem->COMP2_base;
  COMP12_COMMON_BASE = mem->COMP12_COMMON_base;
  OPAMP_BASE = mem->OPAMP_base;
  OPAMP1_BASE = mem->OPAMP1_base;
  OPAMP2_BASE = mem->OPAMP2_base;
  EXTI_BASE = mem->EXTI_base;
  EXTI_D1_BASE = mem->EXTI_D1_base;
  EXTI_D2_BASE = mem->EXTI_D2_base;
  TIM1_BASE = mem->TIM1_base;
  SPI1_BASE = mem->SPI1_base;
  TIM8_BASE = mem->TIM8_base;
  USART1_BASE = mem->USART1_base;
  TIM12_BASE = mem->TIM12_base;
  TIM15_BASE = mem->TIM15_base;
  TIM16_BASE = mem->TIM16_base;
  TIM17_BASE = mem->TIM17_base;
  SAI1_BASE = mem->SAI1_base;
  SAI1_Block_A_BASE = mem->SAI1_Block_A_base;
  SAI1_Block_B_BASE = mem->SAI1_Block_B_base;
  SAI4_BASE = mem->SAI4_base;
  SAI4_Block_A_BASE = mem->SAI4_Block_A_base;
  SAI4_Block_B_BASE = mem->SAI4_Block_B_base;
  SPDIFRX_BASE = mem->SPDIFRX_base;
  DFSDM1_Channel0_BASE = mem->DFSDM1_Channel0_base;
  DFSDM1_Channel1_BASE = mem->DFSDM1_Channel1_base;
  DFSDM1_Channel2_BASE = mem->DFSDM1_Channel2_base;
  DFSDM1_Channel3_BASE = mem->DFSDM1_Channel3_base;
  DFSDM1_Channel4_BASE = mem->DFSDM1_Channel4_base;
  DFSDM1_Channel5_BASE = mem->DFSDM1_Channel5_base;
  DFSDM1_Channel6_BASE = mem->DFSDM1_Channel6_base;
  DFSDM1_Channel7_BASE = mem->DFSDM1_Channel7_base;
  DFSDM1_Filter0_BASE = mem->DFSDM1_Filter0_base;
  DFSDM1_Filter1_BASE = mem->DFSDM1_Filter1_base;
  DFSDM1_Filter2_BASE = mem->DFSDM1_Filter2_base;
  DFSDM1_Filter3_BASE = mem->DFSDM1_Filter3_base;
  DMA2D_BASE = mem->DMA2D_base;
  DCMI_BASE = mem->DCMI_base;
  PSSI_BASE = mem->PSSI_base;
  RCC_BASE = mem->RCC_base;
  FLASH_BASE = mem->FLASH_base;
  CRC_BASE = mem->CRC_base;
  GPIOA_BASE = mem->GPIOA_base;
  GPIOB_BASE = mem->GPIOB_base;
  GPIOC_BASE = mem->GPIOC_base;
  GPIOD_BASE = mem->GPIOD_base;
  GPIOE_BASE = mem->GPIOE_base;
  GPIOF_BASE = mem->GPIOF_base;
  GPIOG_BASE = mem->GPIOG_base;
  GPIOH_BASE = mem->GPIOH_base;
  GPIOJ_BASE = mem->GPIOJ_base;
  GPIOK_BASE = mem->GPIOK_base;
  ADC1_BASE = mem->ADC1_base;
  ADC2_BASE = mem->ADC2_base;
  ADC3_BASE = mem->ADC3_base;
  ADC3_COMMON_BASE = mem->ADC3_COMMON_base;
  ADC12_COMMON_BASE = mem->ADC12_COMMON_base;
  RNG_BASE = mem->RNG_base;
  SDMMC2_BASE = mem->SDMMC2_base;
  DLYB_SDMMC2_BASE = mem->DLYB_SDMMC2_base;
  FMAC_BASE = mem->FMAC_base;
  CORDIC_BASE = mem->CORDIC_base;
  BDMA_BASE = mem->BDMA_base;
  BDMA_Channel0_BASE = mem->BDMA_Channel0_base;
  BDMA_Channel1_BASE = mem->BDMA_Channel1_base;
  BDMA_Channel2_BASE = mem->BDMA_Channel2_base;
  BDMA_Channel3_BASE = mem->BDMA_Channel3_base;
  BDMA_Channel4_BASE = mem->BDMA_Channel4_base;
  BDMA_Channel5_BASE = mem->BDMA_Channel5_base;
  BDMA_Channel6_BASE = mem->BDMA_Channel6_base;
  BDMA_Channel7_BASE = mem->BDMA_Channel7_base;
  RAMECC1_BASE = mem->RAMECC1_base;
  RAMECC1_Monitor1_BASE = mem->RAMECC1_Monitor1_base;
  RAMECC1_Monitor2_BASE = mem->RAMECC1_Monitor2_base;
  RAMECC1_Monitor3_BASE = mem->RAMECC1_Monitor3_base;
  RAMECC1_Monitor4_BASE = mem->RAMECC1_Monitor4_base;
  RAMECC1_Monitor5_BASE = mem->RAMECC1_Monitor5_base;
  RAMECC1_Monitor6_BASE = mem->RAMECC1_Monitor6_base;
  RAMECC2_BASE = mem->RAMECC2_base;
  RAMECC2_Monitor1_BASE = mem->RAMECC2_Monitor1_base;
  RAMECC2_Monitor2_BASE = mem->RAMECC2_Monitor2_base;
  RAMECC2_Monitor3_BASE = mem->RAMECC2_Monitor3_base;
  RAMECC3_BASE = mem->RAMECC3_base;
  RAMECC3_Monitor1_BASE = mem->RAMECC3_Monitor1_base;
  RAMECC3_Monitor2_BASE = mem->RAMECC3_Monitor2_base;
  DMAMUX2_BASE = mem->DMAMUX2_base;
  DMAMUX2_Channel0_BASE = mem->DMAMUX2_Channel0_base;
  DMAMUX2_Channel1_BASE = mem->DMAMUX2_Channel1_base;
  DMAMUX2_Channel2_BASE = mem->DMAMUX2_Channel2_base;
  DMAMUX2_Channel3_BASE = mem->DMAMUX2_Channel3_base;
  DMAMUX2_Channel4_BASE = mem->DMAMUX2_Channel4_base;
  DMAMUX2_Channel5_BASE = mem->DMAMUX2_Channel5_base;
  DMAMUX2_Channel6_BASE = mem->DMAMUX2_Channel6_base;
  DMAMUX2_Channel7_BASE = mem->DMAMUX2_Channel7_base;
  DMAMUX2_RequestGenerator0_BASE = mem->DMAMUX2_RequestGenerator0_base;
  DMAMUX2_RequestGenerator1_BASE = mem->DMAMUX2_RequestGenerator1_base;
  DMAMUX2_RequestGenerator2_BASE = mem->DMAMUX2_RequestGenerator2_base;
  DMAMUX2_RequestGenerator3_BASE = mem->DMAMUX2_RequestGenerator3_base;
  DMAMUX2_RequestGenerator4_BASE = mem->DMAMUX2_RequestGenerator4_base;
  DMAMUX2_RequestGenerator5_BASE = mem->DMAMUX2_RequestGenerator5_base;
  DMAMUX2_RequestGenerator6_BASE = mem->DMAMUX2_RequestGenerator6_base;
  DMAMUX2_RequestGenerator7_BASE = mem->DMAMUX2_RequestGenerator7_base;
  DMAMUX2_ChannelStatus_BASE = mem->DMAMUX2_ChannelStatus_base;
  DMAMUX2_RequestGenStatus_BASE = mem->DMAMUX2_RequestGenStatus_base;
  DMA2_BASE = mem->DMA2_base;
  DMA2_Stream0_BASE = mem->DMA2_Stream0_base;
  DMA2_Stream1_BASE = mem->DMA2_Stream1_base;
  DMA2_Stream2_BASE = mem->DMA2_Stream2_base;
  DMA2_Stream3_BASE = mem->DMA2_Stream3_base;
  DMA2_Stream4_BASE = mem->DMA2_Stream4_base;
  DMA2_Stream5_BASE = mem->DMA2_Stream5_base;
  DMA2_Stream6_BASE = mem->DMA2_Stream6_base;
  DMA2_Stream7_BASE = mem->DMA2_Stream7_base;
  DMA1_BASE = mem->DMA1_base;
  DMA1_Stream0_BASE = mem->DMA1_Stream0_base;
  DMA1_Stream1_BASE = mem->DMA1_Stream1_base;
  DMA1_Stream2_BASE = mem->DMA1_Stream2_base;
  DMA1_Stream3_BASE = mem->DMA1_Stream3_base;
  DMA1_Stream4_BASE = mem->DMA1_Stream4_base;
  DMA1_Stream5_BASE = mem->DMA1_Stream5_base;
  DMA1_Stream6_BASE = mem->DMA1_Stream6_base;
  DMA1_Stream7_BASE = mem->DMA1_Stream7_base;
  DMAMUX1_BASE = mem->DMAMUX1_base;
  DMAMUX1_Channel0_BASE = mem->DMAMUX1_Channel0_base;
  DMAMUX1_Channel1_BASE = mem->DMAMUX1_Channel1_base;
  DMAMUX1_Channel2_BASE = mem->DMAMUX1_Channel2_base;
  DMAMUX1_Channel3_BASE = mem->DMAMUX1_Channel3_base;
  DMAMUX1_Channel4_BASE = mem->DMAMUX1_Channel4_base;
  DMAMUX1_Channel5_BASE = mem->DMAMUX1_Channel5_base;
  DMAMUX1_Channel6_BASE = mem->DMAMUX1_Channel6_base;
  DMAMUX1_Channel7_BASE = mem->DMAMUX1_Channel7_base;
  DMAMUX1_Channel8_BASE = mem->DMAMUX1_Channel8_base;
  DMAMUX1_Channel9_BASE = mem->DMAMUX1_Channel9_base;
  DMAMUX1_Channel10_BASE = mem->DMAMUX1_Channel10_base;
  DMAMUX1_Channel11_BASE = mem->DMAMUX1_Channel11_base;
  DMAMUX1_Channel12_BASE = mem->DMAMUX1_Channel12_base;
  DMAMUX1_Channel13_BASE = mem->DMAMUX1_Channel13_base;
  DMAMUX1_Channel14_BASE = mem->DMAMUX1_Channel14_base;
  DMAMUX1_Channel15_BASE = mem->DMAMUX1_Channel15_base;
  DMAMUX1_RequestGenerator0_BASE = mem->DMAMUX1_RequestGenerator0_base;
  DMAMUX1_RequestGenerator1_BASE = mem->DMAMUX1_RequestGenerator1_base;
  DMAMUX1_RequestGenerator2_BASE = mem->DMAMUX1_RequestGenerator2_base;
  DMAMUX1_RequestGenerator3_BASE = mem->DMAMUX1_RequestGenerator3_base;
  DMAMUX1_RequestGenerator4_BASE = mem->DMAMUX1_RequestGenerator4_base;
  DMAMUX1_RequestGenerator5_BASE = mem->DMAMUX1_RequestGenerator5_base;
  DMAMUX1_RequestGenerator6_BASE = mem->DMAMUX1_RequestGenerator6_base;
  DMAMUX1_RequestGenerator7_BASE = mem->DMAMUX1_RequestGenerator7_base;
  DMAMUX1_ChannelStatus_BASE = mem->DMAMUX1_ChannelStatus_base;
  DMAMUX1_RequestGenStatus_BASE = mem->DMAMUX1_RequestGenStatus_base;
  FMC_Bank1_R_BASE = mem->FMC_Bank1_R_base;
  FMC_Bank1E_R_BASE = mem->FMC_Bank1E_R_base;
  FMC_Bank2_R_BASE = mem->FMC_Bank2_R_base;
  FMC_Bank3_R_BASE = mem->FMC_Bank3_R_base;
  FMC_Bank5_6_R_BASE = mem->FMC_Bank5_6_R_base;
  OCTOSPI1_BASE = mem->OCTOSPI1_base;
  DLYB_OCTOSPI1_BASE = mem->DLYB_OCTOSPI1_base;
  OCTOSPI2_BASE = mem->OCTOSPI2_base;
  DLYB_OCTOSPI2_BASE = mem->DLYB_OCTOSPI2_base;
  OCTOSPIM_BASE = mem->OCTOSPIM_base;
  SDMMC1_BASE = mem->SDMMC1_base;
  DLYB_SDMMC1_BASE = mem->DLYB_SDMMC1_base;
  DBGMCU_BASE = mem->DBGMCU_base;
  HSEM_BASE = mem->HSEM_base;
  HSEM_COMMON_BASE = mem->HSEM_COMMON_base;
  LTDC_BASE = mem->LTDC_base;
  LTDC_Layer1_BASE = mem->LTDC_Layer1_base;
  LTDC_Layer2_BASE = mem->LTDC_Layer2_base;
  MDIOS_BASE = mem->MDIOS_base;
  ETH_BASE = mem->ETH_base;
  MDMA_BASE = mem->MDMA_base;
  MDMA_Channel0_BASE = mem->MDMA_Channel0_base;
  MDMA_Channel1_BASE = mem->MDMA_Channel1_base;
  MDMA_Channel2_BASE = mem->MDMA_Channel2_base;
  MDMA_Channel3_BASE = mem->MDMA_Channel3_base;
  MDMA_Channel4_BASE = mem->MDMA_Channel4_base;
  MDMA_Channel5_BASE = mem->MDMA_Channel5_base;
  MDMA_Channel6_BASE = mem->MDMA_Channel6_base;
  MDMA_Channel7_BASE = mem->MDMA_Channel7_base;
  MDMA_Channel8_BASE = mem->MDMA_Channel8_base;
  MDMA_Channel9_BASE = mem->MDMA_Channel9_base;
  MDMA_Channel10_BASE = mem->MDMA_Channel10_base;
  MDMA_Channel11_BASE = mem->MDMA_Channel11_base;
  MDMA_Channel12_BASE = mem->MDMA_Channel12_base;
  MDMA_Channel13_BASE = mem->MDMA_Channel13_base;
  MDMA_Channel14_BASE = mem->MDMA_Channel14_base;
  MDMA_Channel15_BASE = mem->MDMA_Channel15_base;
  USB1_OTG_HS_BASE = mem->USB1_OTG_HS_base;

  //GPV_BASE = mem->GPV_base;

  Simulator_arena_base = mem->arena_base;
}

#endif // SIMULATOR
